app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:4000

organization:
  name: Acme Corporation

backend:
  baseUrl: http://localhost:8080
  listen: 0.0.0.0:8080
  cors:
    origin: http://localhost:4000
    methods: [GET, POST, PUT, DELETE]
    credentials: true

proxy:
  '/test':
    target: 'https://example.com'
    changeOrigin: true

techdocs:
  storageUrl: https://techdocs-mock-sites.storage.googleapis.com

auth:
  providers: {}
